{% set name = "mypy" %}
{% set version = "0.600" %}
{% set sha256 = "bc251cb31bc236d9fe4bcc442c994c45fff2541f7161ee52dc949741fe9ca3dd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - mypy=mypy.__main__:console_entry
    - stubgen=mypy.stubgen:main
    - dmypy=mypy.dmypy:main
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [py2k]

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - typed-ast >=1.1.0,<1.2.0
    - psutil >=5.4.0,<5.5.0

test:
  imports:
    - mypy
    - mypy.plugins
    - mypy.server
    - mypy.test
  commands:
    - mypy --help
    - stubgen --help
    - dmypy --help

about:
  home: http://www.mypy-lang.org/
  license: MIT
  license_family: MIT
  # https://github.com/python/mypy/issues/4247
  # license_file: LICENSE
  summary: Optional static typing for Python
  description: |
    Add type annotations to your Python programs, and use mypy to type check
    them. Mypy is essentially a Python linter on steroids, and it can catch
    many programming errors by analyzing your program, withoutactually having
    to run it.  Mypy has a powerful type system with features such as type
    inference, gradual typing, generics and union types.
  doc_url: http://mypy.readthedocs.io
  dev_url: https://github.com/python/mypy

extra:
  recipe-maintainers:
    - nehaljwani
